#
# Define individual supplement paths
#

VBRDF_PATH   = $(VLIDORT_VSUP_PATH)/vbrdf
VSLEAVE_PATH = $(VLIDORT_VSUP_PATH)/vsleave

#
# Include individual supplement makefiles
#

include $(VBRDF_PATH)/makefile.vbrdf
include $(VSLEAVE_PATH)/makefile.vsleave
