#!/usr/bin/perl -w

# $Id: f90ps,v 1.3 2008/05/23 18:41:02 bmy Exp $

=head1 NAME

F90PS

=head1 SYNOPSIS

f90ps [ myfile1.F90 ... myfileN.F90 | *.F90 ]

=head1 REQUIRES

Perl 5.003
protex
dvips
latex

=head1 EXPORTS

none

=head1 DESCRIPTION

f90ps
Wrapper script to call the "protex" script, which converts header comments from
F90 routines into a LaTeX document.  The LaTeX document is then converted into
a PostScript document with the "latex" and "dvips" commands.  

Output Filenames: 
LaTeX file      : output.tex
PostScript file : output.ps

=head1 METHODS

&main : Driver routine

=head1 MODIFICATION HISTORY

bmy, 22 May 2008 - INITIAL VERSION

Bob Yantosca (yantosca@seas.harvard.edu)

=head1 SEE ALSO

protex
dvips
dvipdf
latex2html
f90pdf

=head1 COPYRIGHT

Copyright 2008, Bob Yantosca.  All rights reserved.

=cut

require 5.003;        # need this version of Perl or newer
use English;          # Use English language
use Carp;             # Get detailed error messages
use strict;           # Use IMPLICIT NONE-like strict syntax

#------------------------------------------------------------------------------

sub main() {

  #==========================================================================
  # MAIN is the driver routine for the script.
  #==========================================================================

  # Error check #of arguments
  if ( scalar( @ARGV ) == 0 ) { 
    print "Usage: f90ps [ myfile1.F90 ... myfileN.F90 | *.F90 ]\n"; 
    exit(1); 
  }

  # Initialization
  my $texFile = "output.tex";
  my $dviFile = "output.dvi";
  my $psFile  = "output.ps";

  # Remove pre-existing files
  if ( -f $texFile ) { unlink( $texFile ); }
  if ( -f $psFile  ) { unlink( $psFile  ); }

  # Call "protex" to convert comments to make a *.tex file
  # Pipe the output from all files into a single file
  # The -s option only prints code headers
  # The -f option suppresses source code headers
  qx( protex -s -f @ARGV > $texFile );

  # 1st LaTeX pass
  if ( $? == 0 ) { qx( latex $texFile );                          }
  else           { print "Error in 1st latex pass!\n"; return(1); }

  # 2nd LaTeX pass
  if ( $? == 0 ) { qx( latex $texFile );                          }
  else           { print "Error in 2nd latex pass!\n"; return(2); }

  # 3rd LaTeX pass
  if ( $? == 0 ) { qx( latex $texFile );                          }
  else           { print "Error in 3rd latex pass!\n"; return(3); }

  # Convert the DVI file to PostScript
  if ( $? == 0 ) { qx( dvips $dviFile -o $psFile );               }
  else           { print "Error in dvips pass!\n"; return(4);     }

  # Remove temporary files
  if ( $? == 0 ) { qx( rm *.aux *.dvi *.log *.toc ); }
    
  # Return w/ error code
  return( $? );
}

#------------------------------------------------------------------------------

# Call main program
main(); 

# Exit back to shell w/ error code
exit( $? );
